"""
Django settings for choco_reddit project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from os.path import dirname, abspath, join
from types import MappingProxyType

from corsheaders.defaults import default_methods, default_headers
from environ import Env

BASE_DIR = dirname(dirname(abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# environment variables
env = Env()
Env.read_env()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = ('*',)

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',

    'authorization',
    'feed',
)

MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

ROOT_URLCONF = 'choco_reddit.urls'

TEMPLATES = (
    MappingProxyType({
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': (join(BASE_DIR, 'templates'),),
        'APP_DIRS': True,
        'OPTIONS': MappingProxyType({
            'context_processors': (
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ),
        }),
    }),
)

WSGI_APPLICATION = 'choco_reddit.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = MappingProxyType({
    'default': env.db()
})

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = (
    MappingProxyType({
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    }),
    MappingProxyType({
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    }),
    MappingProxyType({
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    }),
    MappingProxyType({
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    }),
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# CORS

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_METHODS = default_methods
CORS_ALLOW_HEADERS = default_headers
CORS_ALLOW_CREDENTIALS = True

# Reddit

REDDIT_BASE_URL = 'https://oauth.reddit.com/'
REDDIT_REDIRECT_URL = env('REDDIT_REDIRECT_URL')
REDDIT_CLIENT_SECRET = env('REDDIT_CLIENT_SECRET')
REDDIT_CLIENT_ID = env('REDDIT_CLIENT_ID')
