version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass


  django:
    build: ./
    command: ./entrypoint.sh
    volumes:
      - ./:/choco_reddit:rw
      - ./.env:/choco_reddit/choco_reddit/.env
    depends_on:
      - db
    ports:
      - 8000:8000
